# Generated by Django 6.0 on 2025-12-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_file_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='certificates/'),
        ),
    ]
